name: flutter_application_1
description: "Aplicación de prueba"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # dependencia para la base de datos
  sqflite: ^2.3.3+1
  path: ^1.8.3

  #dependencia para el uso de google maps
  google_maps_flutter: ^2.0.6
flutter:
  uses-material-design: true
  assets:
    - assets/lucario.png
    - assets/login.png
